### ISSUE TITLE
Agregar a Alexis como docente

### ISSUE THREAD

**Issue by CrossNox** [orga-de-datos/orga-de-datos.github.io#4]
- [ ] agregar datos en https://github.com/orga-de-datos/orga-de-datos.github.io/blob/master/_data/docentes.yml
- [ ] agregar foto **cuadrada** en https://github.com/orga-de-datos/orga-de-datos.github.io/tree/master/assets/images/docentes

**Comment by asoifer** [comment]
Sitio actualizado, cierro el issue.
